<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE venue [
  <!ELEMENT venue (id,issue,section,category,name,thumb,image,critic_choice,hot_seat,website,opentime,excerpt,min_price,max_price,views,data_add,data_change,link,addresses,feature,related_venues)>
  
  <!ELEMENT feature (id,issue,type,local,link,rating,excerpt,review,author,data_add,data_change,title,image,thumb,views)>
  <!ELEMENT addresses (address_slot)>
  <!ELEMENT address_slot (location,address,postcode,phone,near_station,buses)>
  <!ELEMENT related_venues (related_link)>
  <!ELEMENT related_link (kind,link)>
  
  <!ELEMENT id (CDATA)>
  <!ELEMENT issue (CDATA)>
  <!ELEMENT section (CDATA)>

  <!ELEMENT category (CDATA)>
  <!ELEMENT name (CDATA)>
  <!ELEMENT thumb (CDATA)>
  <!ELEMENT image (CDATA)>
  <!ELEMENT size1 (CDATA)>
  <!ELEMENT critic_choice (CDATA)>
  <!ELEMENT hot_seat (CDATA)>
  <!ELEMENT website (CDATA)>
  <!ELEMENT opentime (CDATA)>

  <!ELEMENT excerpt (CDATA)>
  <!ELEMENT min_price (CDATA)>
  <!ELEMENT max_price (CDATA)>
  <!ELEMENT views (CDATA)>
  <!ELEMENT data_add (CDATA)>
  <!ELEMENT data_change (CDATA)>
  <!ELEMENT link (CDATA)>
  
  <!ELEMENT type (CDATA)>
  <!ELEMENT local (CDATA)>

  <!ELEMENT rating (CDATA)>
  <!ELEMENT review (CDATA)>
  <!ELEMENT author (CDATA)>
  <!ELEMENT title (CDATA)>
  
  <!ELEMENT location (CDATA)>
  <!ELEMENT address (CDATA)>
  <!ELEMENT postcode (CDATA)>
  <!ELEMENT phone (CDATA)>
  <!ELEMENT near_station (CDATA)>

  <!ELEMENT buses (CDATA)>
  
  <!ELEMENT kind (CDATA)>
]>
<venue>
	<id>2524</id>
	<issue>43</issue>
	<section>Performance</section>
	<category>Theatre</category>

	<name>Singapore Repertory Theatre</name>
	<critic_choice>N</critic_choice>
	<hot_seat>N</hot_seat>
	<website>http://www.srt.com.sg/</website>
	<opentime><![CDATA[]]></opentime>
	<excerpt><![CDATA[This is the Singapore Repertory Theatre office, but most productions are staged at <a href="http://www.timeoutsingapore.com/performance/venues/comedy/dbs-arts-centre">DBS Arts Centre</a>.]]></excerpt>
	<min_price>0.00</min_price>

	<max_price>0.00</max_price>
	<views>33</views>
	<data_add>Fri, 27 Aug 2010 08:35:37 +0000</data_add>
	<data_change>Fri, 27 Aug 2010 08:36:45 +0000</data_change>
	<redirect></redirect>
	<standfirst></standfirst>
	<gallery>0</gallery>

	<top_start>0000-00-00</top_start>
	<top_end>0000-00-00</top_end>
	<top_premium></top_premium>
	<top_platinum></top_platinum>
	<has_top>N</has_top>
	<top_logo></top_logo>
	<top_excerpt></top_excerpt>

	<link>http://www.timeoutsingapore.com/performance/venues/theatre/singapore-repertory-theatre</link>
<tags>
	<tag>Performance</tag>
</tags>
	<addresses>
		<address_slot>
			<location>Robertson Walk #02-08</location>
			<address>11 Unity Street</address>

			<postcode>237995</postcode>
			<phone>6221 5585</phone>
			<near_station>Clarke Quay</near_station>
			<buses>64, 123, 143</buses>
		</address_slot>
	</addresses>
	<related_venues>

		<related_link>
			<kind>restaurant</kind>
			<link>http://www.timeoutsingapore.com/xmlapi/xml_detail?venue=34&amp;key=ffab6a24c60f562ecf705130a36c1d1e</link>
		</related_link>
		<related_link>
			<kind>restaurant</kind>
			<link>http://www.timeoutsingapore.com/xmlapi/xml_detail?venue=1578&amp;key=ffab6a24c60f562ecf705130a36c1d1e</link>

		</related_link>
		<related_link>
			<kind>restaurant</kind>
			<link>http://www.timeoutsingapore.com/xmlapi/xml_detail?venue=1875&amp;key=ffab6a24c60f562ecf705130a36c1d1e</link>
		</related_link>
		<related_link>
			<kind>restaurant</kind>

			<link>http://www.timeoutsingapore.com/xmlapi/xml_detail?venue=1861&amp;key=ffab6a24c60f562ecf705130a36c1d1e</link>
		</related_link>
		<related_link>
			<kind>restaurant</kind>
			<link>http://www.timeoutsingapore.com/xmlapi/xml_detail?venue=1644&amp;key=ffab6a24c60f562ecf705130a36c1d1e</link>
		</related_link>

		<related_link>
			<kind>bar</kind>
			<link>http://www.timeoutsingapore.com/xmlapi/xml_detail?venue=98&amp;key=ffab6a24c60f562ecf705130a36c1d1e</link>
		</related_link>
		<related_link>
			<kind>bar</kind>
			<link>http://www.timeoutsingapore.com/xmlapi/xml_detail?venue=1693&amp;key=ffab6a24c60f562ecf705130a36c1d1e</link>

		</related_link>
		<related_link>
			<kind>bar</kind>
			<link>http://www.timeoutsingapore.com/xmlapi/xml_detail?venue=633&amp;key=ffab6a24c60f562ecf705130a36c1d1e</link>
		</related_link>
		<related_link>
			<kind>bar</kind>

			<link>http://www.timeoutsingapore.com/xmlapi/xml_detail?venue=964&amp;key=ffab6a24c60f562ecf705130a36c1d1e</link>
		</related_link>
		<related_link>
			<kind>bar</kind>
			<link>http://www.timeoutsingapore.com/xmlapi/xml_detail?venue=648&amp;key=ffab6a24c60f562ecf705130a36c1d1e</link>
		</related_link>

	</related_venues>
</venue>

